### ISSUE TITLE
Chinese (Simplified) translate

### ISSUE THREAD

**Issue by baka-gourd** [SpaceboyRoss01/MSGundamMod#5]
Hey,I can't **submit** a translation, this is [zh_CN.lang](https://paste.ubuntu.com/p/vQBBdDvFXk/)

**Comment by 0999312** [comment]
这个zhCN问题挺多啊。。。。。。有时间我重写一份好了。

**Comment by baka-gourd** [comment]
o，wiki快看吐了233

**Comment by RossComputerGuy** [comment]
Translation was rejected because we’re not yet ready for adding translations.
